# Generated by Django 3.1.12 on 2025-08-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
