# Generated by Django 3.1.12 on 2025-08-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/no-image.png', null=True, upload_to='category_images/'),
        ),
    ]
