# Generated by Django 3.1.12 on 2025-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/no-image.png', null=True, upload_to='subcategory_images/'),
        ),
    ]
