# Generated by Django 3.1.12 on 2025-08-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
