# Generated by Django 3.1.12 on 2025-08-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20250829_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='payment_status',
            field=models.CharField(default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='grand_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerorder')),
            ],
        ),
    ]
