# Generated by Django 3.1.12 on 2025-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_productstocknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
