# Generated by Django 3.1.12 on 2025-08-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customerorder_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
