# Generated by Django 3.1.12 on 2025-08-29 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0009_auto_20250829_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerOrderHistory',
            new_name='CustomerOrder',
        ),
    ]
