# Generated by Django 3.1.12 on 2025-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('product_count', models.IntegerField(default=0)),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Owner Statistic',
                'verbose_name_plural': 'Owner Statistics',
                'db_table': 'taskpro1_owner_stats',
            },
        ),
    ]
